version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd api
      - npm i
  pre_build:
    commands:
      - npm test
  post_build:
    commands:
      - sls deploy

cache:
  paths:
    - 'node_modules/**/*'