version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd api
      - npm i
      - npm i -g serverless
  pre_build:
    commands:
      - npm test
  post_build:
    commands:
      - serverless deploy

cache:
  paths:
    - 'node_modules/**/*'