service: aws-nodejs 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /{any+}
          method: any
